language:  generic

notifications:
  slack:
    rooms:
      - zeeql:odi4PEJUdmDPkBfjhHIaSdrS

matrix:
    include:
        - os:   osx
          osx_image: xcode11

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - xcodebuild -scheme MacRentals -configuration Debug -target MacRentals | xcpretty
#   - xcodebuild -scheme DVDRental  -configuration Debug -target DVDRental | xcpretty
#   - xcodebuild -scheme "DVDRentalWatch WatchKit App" -configuration Debug | xcpretty
